### PR TITLE
French translation :fr: 

### PR DESCRIPTION
**Pull request by helaili**
It's kind of explicit with the title ☝️

### CODE REVIEW

**Comment by helaili** [comment]
@githubtraining/learning-engineering I have made couple edits on 🇬🇧 pages whenever I spotted a typo.
For the :fr: version, @sophielegrand will gladly proof read

**Comment by brianamarie** [comment]
Thank you so much, @helaili! This is so exciting. ✨ 

@SophieLegrand, once you proofread, let us know here. Then, I'll merge this into a branch on this upstream repository so we can test, and then we can merge into master. 🎉 

cc @githubtraining/programs @githubtraining/learning-engineering @crichID @BonnieC to see awesome translation work 👀 

cc @JasonEtco @githubtraining/learning-engineering - I recall asking this before but I don't remember following up, so I apologize. Is it expected behavior that pull requests from forks do not generate drafts? Can we trigger that manually as org owners so that we can test this without an additional merge step to another upstream branch?

**Comment by JasonEtco** [comment]
> Is it expected behavior that pull requests from forks do not generate drafts?

Unfortunately yes 😞 Not an impossible feat for us to support this, but a non-trivial task that we'll have to do.

> Can we trigger that manually as org owners so that we can test this without an additional merge step to another upstream branch?

No - I'll have a think about how we can "deploy" this manually, but none come to mind right away 🤔 A non-great approach, we can pull in the fork as a course on staging (or in production if we'd like) and do some click testing there.

**Comment by hectorsector** [comment]
@helaili I recreated your work over at https://github.com/githubtraining/introduction-to-github/pull/44. You can collaborate on it with @sophielegrand there, and see new changes deployed by clicking on "View deployment". Feel free to close this PR and resume the work there when ready.

**Comment by lmkeston** [comment]
Closing this PR as the code has been moved to a branch and recreated in [#44](https://github.com/githubtraining/introduction-to-github/pull/44)

**Pull request closed without merging**
