### PR TITLE
French translation 🇫🇷

### PR DESCRIPTION
**Pull request by hectorsector**
This PR recreates the work in https://github.com/githubtraining/introduction-to-github/pull/43 so that we can deploy from this branch and test.

### CODE REVIEW

**Comment by brianamarie** [comment]
Friendly bump on this @helaili - have you had a chance to look over @SophieLegrand's review?

**Comment by helaili** [comment]
I did @brianamarie but as mentioned on [Slack](https://github.slack.com/archives/CC3KANQ8Z/p1587741403171400?thread_ts=1585143654.005100&cid=CC3KANQ8Z) I need push access to be able to commit it back.

**Comment by brianamarie** [comment]
> I did @brianamarie but as mentioned on [Slack](https://github.slack.com/archives/CC3KANQ8Z/p1587741403171400?thread_ts=1585143654.005100&cid=CC3KANQ8Z) I need push access to be able to commit it back.

Ah - I'm so sorry I missed that before. I've opened a PR with entitlements that should unblock you once it's merged. 😄

**Comment by helaili** [comment]
@brianamarie changes have (finally 😊 ) been pushed.

**Comment by brianamarie** [comment]
This is so awesome!!! Thank you so much @helaili and @SophieLegrand! 

I have tested this out (English and French) for the first few steps, and everything looks as expected. 🎉 I am on "comms duty" for the team this week, so I'm going to go ahead and merge, and I'll also keep an eye out on the community forum and Halp in case there are any unexpected issues.

**Pull request merged**
